### PR TITLE
Add the home variable for condor jobs which was causing issues

### PR DESCRIPTION
**Pull request by benkrikler**
#### Reference Issue
Should address issue #162.  I'm currently testing now.
Related to discussion on https://sft.its.cern.ch/jira/browse/SPI-1242

#### What does this pull request implement/fix? Explain your changes.
An issue with condor jobs crashing because rootpy crashes when it look for a HOME environment variable and it can't be found.

### CODE REVIEW

**Comment by benkrikler** [comment]
In addition to adding the home variable to the condor jobs' environments (which proved quite hard!), I'm now also:
1. Building the external libraries with the absolute path to the headers, rather than a relative path
2. Fixed the cmsl1t_batch_status command to check each process properly with condor
3. Make sure the include path for externals is provided to ROOT when we include things
4. Only pass the filename to the script condor runs, the script already takes care of `-c`.

**Comment by benkrikler** [comment]
There were some changes made to "reduce analyzer scope" by @kreczko but I'm a bit unsure how this had ever worked with the batch system; perhaps this part was unfinished? The result of this change meant the config files being written out for each job were unable to be reloaded since the expected format of the analyzer description is different to that of the original.  I've put in several fixes so that analyzers can now be read in as either a list of dictionaries, each of which must contain a name, or it can be a dictionary of dictionaries, in which case the name is taken as the key (which I think was the original design).

**Comment by benkrikler** [comment]
I appreciate this is quite a large PR, but can we merge it in and build on top of it?

**Comment by kreczko** [comment]
Yes, I am currently testing it on lxplus - waiting for results

**Comment by kreczko** [comment]
More work to be done:
```
condor_exec.exe: line 8: cmsl1t: command not found
```

**Pull request merged**
