### PR TITLE
Recalc method to match jets

### PR DESCRIPTION
**Pull request by benkrikler**
Adds a simple method to match between two lists of jets, eg. online vs reconstructed.  
The algorithm works by pairing the closest jets in eta and phi (using a euclidean metric) until no jets remain in either list, or until the only jets that do remain are further apart than some limit, which defaults to dR < 0.5,

Code is in the cmsl1t/recalc sub-package, since I thought this was physics related, rather than in the utils subpackage which I thought was more for software-related functionality.  I'm happy to move it if recalc doesn't seem like an appropriate place.  

Unit tests are in place for the new code.

Should only be merged after #43; the diff here looks longer than it really is because this builds on that work.

### CODE REVIEW

**Comment by kreczko** [comment]
I think rather than `recalc` we probably should but these kind of things (as well as recalc MET) under `modifiers`. At least that's what they are referred to in the configuration.

A modifier should have the public method, `modify(event)`. This method should read bits from the event and attach a **new** attribute. It should raise an excpetion if the the attribute already exists.
We will also need a way to order modifiers. Maybe a `requires` method?

I will try to structure things after this PR and create a new issue for `modifiers`.

**Comment by kreczko** [comment]
BTW: Commit 	960dfbf is also included in PR #43

**Comment by benkrikler** [comment]
Yes, so I think that's a habit from working with Gitlab, where it seems to be smarted at updating the diff when the master branch is updated.  There I was able to make a PR that builds on top of a previous PR that's still open, and when that was closed, the later PR would be updated so that the commits it includes start only from those not yet merged and the diff compares to the HEAD of master.  I hadn't realised Github treated these situations differently, so I'll change this approach in the future.

**Comment by kreczko** [comment]
Please rebase :)

**Pull request closed without merging**
