### PR TITLE
Migrating legacy analyzers

### PR DESCRIPTION
**Pull request by kreczko**
Solving issue #8 

Overview of migrated scripts:
 - [x] makeJetRates.cxx
 - [x] makeJetResolutions.cxx
    - [x] introduce Resolution collection 
 - [x] makeJetTurnons.cxx
 - [ ] makeJetXvsY.cxx
 - [ ] makeRateEfficiency.cxx
 - [ ] makeRates.cxx
 - [ ] makeResolutions.cxx
 - [x] makeTurnons.cxx
 - [ ] makeXvsY.cxx
 - [x] studyTower28MET.cxx
   - [x] introduce Efficiency Collection

### CODE REVIEW

**Comment by benkrikler** [comment]
Hi Luke, 
Sorry for taking so long to review this.  I've been through the key parts of 'common' code that you've added / changed and things look fine. 

I'd be curious to see how much better the code performs with the CachedIndexedTree classes you've added are, compared to accessing the tree without the caches.  I'm also slightly nervous that they give a memory leak, but I'm not sure how the python/C++/ROOT interface handles memory management.
Any thoughts?

**Comment by kreczko** [comment]
I am surprised they give memory leaks, I was hoping to simply extend the caching TreeChain does and just adding the index inversion.
Likely I've done something wrong then.

**Comment by benkrikler** [comment]
No, sorry, I'm not saying they do cause memory leaks, I haven't really checked, I'm just nervous that they might and, since it's a part that would be nasty if there were a leak, I didn't want to merge without checking.  But since you say that TreeChain already does this sort of thing, I'll merge this in then.

Thanks!

**Comment by kreczko** [comment]
@benkrikler : the TTree caching and memory handling is done in TreeChain.
The CachedIndexedTree is created per event and improves things only when they are accessed several times per event.

**Pull request merged**
